# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - terraform/*

variables:
  - name: Region
    value: 'ca-central-1'
  - name: awsConnection
    value: 'sbarbot on barbots (aws)'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SystemsManagerGetParameter@1
  inputs:
    awsCredentials: '$(awsConnection)'
    regionName: '$(Region)'
    readMode: 'hierarchy'
    parameterPath: '/Common/'
    recursive: true
- task: SystemsManagerGetParameter@1
  inputs:
    awsCredentials: $(awsConnection)
    regionName: $(Region)
    readMode: 'hierarchy'
    parameterPath: '/PrepareYourReview/'
    recursive: true
    hierarchyNameTransform: 'leaf'
- task: replacetokens@3
  inputs:
    rootDirectory: 'terraform'
    targetFiles: '**/*.tf'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'fail'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    enableTelemetry: true
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.26'
- task: TerraformTaskV1@0
  displayName: 'Init Terraform'
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    backendServiceAWS: $(backendServiceAWS)
    backendAWSBucketName: $(backendbucket)
    backendAWSKey: $(backendkey)
- task: TerraformTaskV1@0
  displayName: 'Apply Terraform'
  inputs:
    provider: 'aws'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    environmentServiceNameAWS: $(backendServiceAWS)